language: c

compiler:
  - gcc

matrix:
  include:
    - os: linux
      name: Ubuntu 16.04
      dist: xenial
      env:
      - BADGE=Ubuntu_16.04
      - MAKE=make
    - os: linux
      name: Ubuntu 18.04
      dist: bionic
      env:
      - BADGE=Ubuntu_18.04
      - MAKE=make
    - os: windows
      name: Windows
      env:
      - BADGE=Windows
      - MAKE=mingw32-make
#    - os: osx
#      name: OSX
#      env:
#      - BADGE=OSX
#      - MAKE=make

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install octave; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install octave; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install octave.portable --version=4.2.1; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco list octave.portable -lo -v; fi

addons:
  apt:
    packages:
    - octave
    update: true

script:
    - ${MAKE} -C src lib
    - ${MAKE} -C src oct
    - ${MAKE} -C src dll
