language: c

compiler:
  - gcc

jobs:
  include:
    - os: linux
      name: Ubuntu 14.04
      dist: trusty
      env:
      - BADGE=Ubuntu_14.04
      - MAKE=make
    - os: linux
      name: Ubuntu 16.04
      dist: xenial
      env:
      - BADGE=Ubuntu_16.04
      - MAKE=make
    - os: linux
      name: Ubuntu 18.04
      dist: bionic
      env:
      - BADGE=Ubuntu_18.04
      - MAKE=make
    - os: linux
      name: Ubuntu 20.04
      dist: focal
      env:
      - BADGE=Ubuntu_20.04
      - MAKE=make
    - os: linux
      name: Ubuntu 22.04
      dist: jammy
      env:
      - BADGE=Ubuntu_22.04
      - MAKE=make
    - os: windows
      name: Windows
      env:
      - BADGE=Windows
      - MAKE=mingw32-make
    - os: osx
      name: OSX
      osx_image: xcode13.4
      env:
      - BADGE=OSX
      - MAKE=make

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install liboctave-dev; fi
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
#        choco install octave.portable --version=4.2.1;
#        export PATH=/c/ProgramData/chocolatey/lib/octave.portable/tools/octave/bin:.:${PATH};
#    fi

addons:
  apt:
    packages:
    - liboctave-dev
    update: true

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
         octave-cli --eval "addpath(pwd);cd test;run_zmat_test";
      fi
    - ${MAKE} -C src lib
    - ${MAKE} -C example/c all
    - ${MAKE} -C src dll
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
         cp lib/* example/c;
      fi
    - ${MAKE} -C example/c all LIBTYPE=
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
         ls -lt lib;
         DYLD_LIBRARY_PATH=lib example/c/testzmat;
      else
         LD_LIBRARY_PATH=lib example/c/testzmat;
      fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
         ${MAKE} -C src oct;
         octave-cli --eval "addpath(pwd);cd test;run_zmat_test";
      fi
