#!/bin/sh
# amalgamate.sh — generate include/zmat.h as a single-header-only library
# Sources: zmatlib.h/c + miniz.h/c
# Supported codecs: zlib, gzip, base64 (via embedded miniz)
# Optional codecs (lzma, lz4, zstd, blosc2) are excluded from this header.
#
# Usage: sh amalgamate.sh [outfile]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTFILE="${1:-${SCRIPT_DIR}/../include/zmat.h}"

INCDIR="${SCRIPT_DIR}/../include"
MINIZ_H="${SCRIPT_DIR}/miniz/miniz.h"
MINIZ_C="${SCRIPT_DIR}/miniz/miniz.c"
ZMATLIB_H="${INCDIR}/zmatlib.h"
ZMATLIB_C="${SCRIPT_DIR}/zmatlib.c"

for f in "$MINIZ_H" "$MINIZ_C" "$ZMATLIB_H" "$ZMATLIB_C"; do
    [ -f "$f" ] || { echo "amalgamate.sh: missing $f" >&2; exit 1; }
done

echo "Generating $OUTFILE ..." >&2

# Redirect all stdout to the output file from here on
exec > "$OUTFILE"

# ---------- preamble ----------
cat << 'PREAMBLE'
/* zmat.h — amalgamated single-header-only library
 * Generated by "make header" from zmatlib + miniz
 *
 * Supported codecs: zlib, gzip, base64 (via embedded miniz)
 * Optional codecs (lzma, lz4, zstd, blosc2) are not included.
 *
 * HOW TO USE
 *   In exactly one .c/.cpp translation unit define ZMAT_IMPLEMENTATION
 *   before including this header:
 *
 *     #define ZMAT_IMPLEMENTATION
 *     #include "zmat.h"
 *
 *   All other files just:
 *     #include "zmat.h"
 *
 * COMPILE FLAGS (automatically set inside ZMAT_IMPLEMENTATION; listed here
 * so callers that compile zmatlib.c separately know what to pass):
 *   -DNO_ZLIB    use embedded miniz instead of system zlib
 *   -DNO_LZMA    exclude lzma/lzip codec
 *   -DNO_LZ4     exclude lz4/lz4hc codec
 *   -DNO_ZSTD    exclude zstd codec
 *   -DNO_BLOSC2  exclude blosc2 meta-compressor
 */

#ifndef ZMAT_AMALGAMATED_H
#define ZMAT_AMALGAMATED_H

PREAMBLE

# ---------- miniz.h (no native include guard, so wrap one) ----------
# The #ifndef MINIZ_NO_ARCHIVE_APIS block (ZIP API) runs to the end of miniz.h
# and miniz.c (~448 + ~4867 = ~5315 lines).  zmat only uses deflate/inflate/crc32;
# ZIP is never needed so we physically strip it and also define the macro to suppress
# the #include <time.h> that miniz.h guards with the same flag.
echo "/* ======== miniz.h ======== */"
echo "#ifndef ZMAT_MINIZ_H_INCLUDED"
echo "#define ZMAT_MINIZ_H_INCLUDED"
echo "#define MINIZ_NO_ARCHIVE_APIS"
awk '/^#ifndef MINIZ_NO_ARCHIVE_APIS$/ { exit } { print }' "$MINIZ_H"
echo "#endif /* ZMAT_MINIZ_H_INCLUDED */"
echo ""

# ---------- zmatlib.h (public API) ----------
echo "/* ======== zmatlib.h ======== */"
cat "$ZMATLIB_H"
echo ""

# ---------- open ZMAT_IMPLEMENTATION guard ----------
cat << 'IMPL_OPEN'
#ifdef ZMAT_IMPLEMENTATION

/* Force embedded miniz and disable optional codecs not in this amalgamation */
#ifndef NO_ZLIB
#  define NO_ZLIB
#endif
#ifndef NO_LZMA
#  define NO_LZMA
#endif
#ifndef NO_LZ4
#  define NO_LZ4
#endif
#ifndef NO_ZSTD
#  define NO_ZSTD
#endif
#ifndef NO_BLOSC2
#  define NO_BLOSC2
#endif

IMPL_OPEN

# ---------- miniz.c (strip leading #include "miniz.h" and ZIP archive block) ----------
echo "/* ======== miniz.c ======== */"
awk 'NR==1 && /^#include "miniz\.h"$/ { next }
     /^#ifndef MINIZ_NO_ARCHIVE_APIS$/ { exit }
     { print }' "$MINIZ_C"
echo ""
echo "/* ======== end miniz.c ======== */"
echo ""

# ---------- zmatlib.c (strip includes already covered by the header) ----------
# Stripped lines:
#   #include "zmatlib.h"      — already in this header
#   #include "zlib.h"         — miniz replaces zlib; NO_ZLIB is forced above
#   #include "miniz.h"        — already embedded at the top of this header
# Everything else (including the #define GZIP_HEADER_SIZE 10 in the #else branch)
# is left intact; NO_ZLIB being defined means the #else branch is compiled.
echo "/* ======== zmatlib.c ======== */"
awk '
  /^#include "zmatlib\.h"$/ { next }
  /^    #include "zlib\.h"$/ { next }
  /^    #include "miniz\.h"$/ { next }
  { print }
' "$ZMATLIB_C"
echo "/* ======== end zmatlib.c ======== */"

# ---------- close guards ----------
cat << 'FOOTER'

#endif /* ZMAT_IMPLEMENTATION */

#endif /* ZMAT_AMALGAMATED_H */
FOOTER

echo "Done: $OUTFILE" >&2
