name: ZMat CI

on: [push, pull_request]

jobs:
  octave_test:
    name: Octave tests
    strategy:
      # tested octave versions: ubuntu-20.04 = 5.2, ubuntu-22.04 = 6.4, macos-11 = 8.1, windows-2019 = 7.3
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, windows-2019]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          [[ "$RUNNER_OS" == "Linux" ]] && sudo apt-get update && sudo apt-get install -y liboctave-dev
          [[ "$RUNNER_OS" == "macOS" ]] && brew install octave
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            curl --retry 3 -kL http://cdimage.debian.org/mirror/gnu.org/gnu/octave/windows/octave-7.3.0-w64-64.7z --output octave_7.3.0.7z
            7z x octave_7.3.0.7z -ooctave -y
            echo "$PWD/octave/octave-7.3.0-w64-64/mingw64/bin" >> $GITHUB_PATH
            echo 'C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\' >> $GITHUB_PATH
          fi
      - name: Build static library
        run: |
          which cc
          which gcc
          which g++
          make -C src lib CC=gcc CXX=g++
          make -C example/c all CC=gcc CXX=g++ LIBTYPE=
          if [ "$TRAVIS_OS_NAME" = "macOS" ]; then
             DYLD_LIBRARY_PATH=lib example/c/testzmat;
          else
             LD_LIBRARY_PATH=lib example/c/testzmat;
          fi
      - name: Build dynamic library
        run: |
          make -C src dll CC=gcc CXX=g++
          make -C example/c all  CC=gcc CXX=g++ LIBTYPE=
          if [ "$RUNNER_OS" = "macOS" ]; then
             DYLD_LIBRARY_PATH=lib example/c/testzmat;
          else
             LD_LIBRARY_PATH=lib example/c/testzmat;
          fi
      - name: Build octave mex
        run: |
          make -C src oct CC=gcc CXX=g++ USERLINKOPT="-v"
      - name: Run octave test
        run: |
          octave-cli --version
          octave-cli --eval "addpath(pwd);cd test;run_zmat_test";

  matlab_test:
    name: MATLAB test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Set up mex gcc (Windows only)
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo 'MW_MINGW64_LOC=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/' >> $GITHUB_ENV
      - name: Build MATLAB mex
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            make -C src mex CC=gcc CXX=g++ MEX="cmd //c mex -f mexopts_msys2_gcc.xml" LINKOPT='-L"C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib"' COMPFLAGS=' '
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            make -C src mex CC=gcc-10 CXX=g++10
          else
            make -C src mex CC=gcc CXX=g++
          fi
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd test;run_zmat_test
