name: ZMat CI

on: [push, pull_request]

jobs:
  octave_test:
    name: Octave tests
    strategy:
      # tested octave versions: ubuntu-20.04 = 5.2, ubuntu-22.04 = 6.4, macos-11 = 8.1, windows-2019 = 7.3
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          [[ "$RUNNER_OS" == "Linux" ]] && sudo apt-get update && sudo apt-get install -y liboctave-dev
          [[ "$RUNNER_OS" == "macOS" ]] && brew install octave
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            curl --retry 3 -kL http://cdimage.debian.org/mirror/gnu.org/gnu/octave/windows/octave-7.3.0-w64-64.7z --output octave_7.3.0.7z
            7z x octave_7.3.0.7z -ooctave -y
            echo 'C:\msys64\mingw64\bin' >> $GITHUB_PATH
          fi
      - name: Install msys2 libraries (Windows only)
        if: ${{ runner.os == 'Windows' }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-winpthreads-git
            base-devel
      - name: Install file search tool everything
        if: ${{ runner.os == 'Windows' }}
        run: |
            choco install es
            es zlib1
            es libz.a
            es liboctinterp.dll
      - name: Build static library
        run: |
          which gcc
          which g++
          make -C src lib CC=gcc CXX=g++
          make -C example/c all CC=gcc CXX=g++ LIBTYPE=
          if [ "$TRAVIS_OS_NAME" = "macOS" ]; then
             DYLD_LIBRARY_PATH=lib example/c/testzmat;
          else
             LD_LIBRARY_PATH=lib example/c/testzmat;
          fi
      - name: Build dynamic library
        run: |
          make -C src dll CC=gcc CXX=g++
          make -C example/c all  CC=gcc CXX=g++ LIBTYPE=
          if [ "$RUNNER_OS" = "macOS" ]; then
             DYLD_LIBRARY_PATH=lib example/c/testzmat;
          else
             LD_LIBRARY_PATH=lib example/c/testzmat;
          fi
      - name: Build octave mex (Windows only)
        if: ${{ runner.os == 'Windows' }}
        shell: msys2 {0}
        run: |
          export PATH="/c/msys64/mingw64/bin":"$PWD/octave/octave-7.3.0-w64-64/mingw64/bin":$PATH
          make -C src oct CC=gcc CXX=g++ USERLINKOPT="-static-libgcc -static-libstdc++ -fstack-protector -L/c/msys64/mingw64/lib -Wl,-Bstatic -lz -lwinpthread -Wl,-Bdynamic -v" CXXLIBS="$PWD/octave/octave-7.3.0-w64-64/mingw64/lib/octave/7.3.0/liboctinterp.dll.a"
          objdump -p zipmat.mex | grep "DLL Name:"
          echo "$PWD/octave/octave-7.3.0-w64-64/mingw64/bin" >> $GITHUB_PATH
      - name: Build octave mex (Linux and Mac)
        if: ${{ runner.os != 'Windows' }}
        run: |
          make -C src oct CC=gcc CXX=g++
      - name: Run octave test (Windows only)
        if: ${{ runner.os == 'Windows' }}
        shell: msys2 {0}
        run: |
          export PATH="$PWD/octave/octave-7.3.0-w64-64/mingw64/bin":$PATH
          octave-cli --version
          octave-cli --eval "addpath(pwd);cd test;run_zmat_test";
      - name: Run octave test (Linux and Mac)
        if: ${{ runner.os != 'Windows' }}
        run: |
          octave-cli --version
          octave-cli --eval "addpath(pwd);cd test;run_zmat_test";

  matlab_test:
    name: MATLAB test
    strategy:
      matrix:
        os: [windows-2019]
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Install msys2 libraries (Windows only)
        if: ${{ runner.os == 'Windows' }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-winpthreads-git
            base-devel
      - name: Set up mex gcc (Windows only)
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo 'MW_MINGW64_LOC=/c/msys64/mingw64' >> $GITHUB_ENV
          echo 'COMPFLAGS=""' >> $GITHUB_ENV
      - name: Build MATLAB mex
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            make -C src mex CC=gcc CXX=g++ MEX="cmd //s //c mex  -f mexopts_msys2_gcc.xml " USERLINKOPT="-v " CXXLIBS="-Lblosc2/lib -L/blosc2/internal-complibs/zstd-1.5.2"
            objdump -p zipmat.mexw* | grep "DLL Name:"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            make -C src mex CC=gcc-10 CXX=g++10
          else
            make -C src mex CC=gcc CXX=g++ CXXLIBS="-static-libgcc"
          fi
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd test;run_zmat_test
